version: '2'
services:
    jhipsterhibernatetutorial-sonar:
        container_name: jhipsterhibernatetutorial-sonar
        image: sonarqube:5.6.1-alpine
        ports:
            - 9000:9000
            - 9092:9092
